import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/navbar/Navbar";
import Footer from "@/components/landing/footer/Footer";
import SmoothScrollProvider from "@/components/landing/providers/SmoothScrollProvider";
import PreloaderProvider from "@/components/landing/providers/PreloaderProvider";
import Preloader from "@/components/landing/preloader/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Navbar />
        <SmoothScrollProvider>
          <PreloaderProvider>
            {/* <Preloader /> */}

            {children}
          </PreloaderProvider>
        </SmoothScrollProvider>
        <Footer />
      </body>
    </html>
  );
}
