import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/landing/navbar/Navbar";
import Footer from "@/components/landing/footer/Footer";
import SmoothScrollProvider from "@/components/landing/providers/SmoothScrollProvider";
import PreloaderProvider from "@/components/landing/providers/PreloaderProvider";
import Preloader from "@/components/landing/preloader/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Space+Mono:wght@400;700&display=swap"
      rel="stylesheet"
    /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
        suppressHydrationWarning={true}
      >
        <Navbar />
          <SmoothScrollProvider>
            <PreloaderProvider>
              {/* <Preloader /> */}

              {children}
            </PreloaderProvider>
          </SmoothScrollProvider>
        <Footer />
      </body>
    </html>
  );
}
